[build]
  command = "npm run build"
  functions = "../../netlify/functions"
  publish = "dist"

[dev]
  command = "npm run develop"
  publish = "client/dist"
  framework = "#custom"
  targetPort = 3000
  port = 8888
